;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        coffee-dedent-line-backspace
        delete-indentation
        eval-last-sexp
        evil-change
        haskell-indentation-delete-backward-char
        indent-for-tab-command
        isearch-forward-regexp
        kill-region-or-backward-word
        markdown-exdent-or-delete
        paredit-backslash
        paredit-backward-slurp-sexp
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-newline
        paredit-open-round
        paredit-semicolon
        paredit-splice-sexp
        paredit-wrap-round
        python-backspace
        python-electric-colon
        python-indent-dedent-line-backspace
        repeat
        save-region-or-current-line
        sgml-slash
        toggle-quotes
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        checkdoc-eval-defun
        describe-key-briefly
        end-of-buffer
        eval-expression
        ido-display-buffer
        ido-switch-buffer
        ido-switch-buffer-other-window
        isearch-backward-regexp
        markdown-export-pdf
        marked
        point-to-register
        smex
        toggle-input-method
        universal-argument-minus
        ))
