;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(describe-key-briefly
                               keyboard-escape-quit
                               evil-backward-word-begin
                               evil-forward-char
                               evil-next-line
                               evil-previous-line
                               evil-change
                               evil-delete-backward-word
                               evil-insert
                               evil-delete
                               evil-backward-char
                               evil-forward-word-end
                               python-indent-dedent-line-backspace
                               indent-for-tab-command
                               isearch-other-control-char
                               isearch-printing-char
                               jump-char-forward
                               jump-char-process-char
                               kill-region-or-backward-word
                               minibuffer-complete-and-exit
                               paredit-forward-delete
                               python-electric-colon
                               paredit-kill))

(setq mc/cmds-to-run-once '(python-backspace
                            isearch-printing-char
                            isearch-other-control-char))



